/**
 * Icon names used by the registries. They are plain string keys so registries stay pure data;
 * the UI maps each key to the export of the same name in the Design System icon module
 * (`@content-ventures/design-system/v3/icons`). A test checks every key exists there.
 * `Sparkles` is reserved for AI actions (README §6); `Megaphone` marks "Novidades"; `BadgeCheck`
 * marks "Aprovações" and `Inbox` the "Início" queue (the DS has no house icon).
 */
export type IconKey =
  | 'Activity'
  | 'Archive'
  | 'AtSign'
  | 'BadgeCheck'
  | 'BarChart3'
  | 'Boxes'
  | 'Building2'
  | 'CalendarDays'
  | 'Captions'
  | 'ChartNoAxesColumn'
  | 'CheckCircle2'
  | 'ClipboardList'
  | 'Clock'
  | 'Download'
  | 'FileSignature'
  | 'FileText'
  | 'FileVideo'
  | 'Gauge'
  | 'Globe'
  | 'Image'
  | 'Inbox'
  | 'LayoutDashboard'
  | 'LayoutList'
  | 'LayoutTemplate'
  | 'ListChecks'
  | 'Loader2'
  | 'Mail'
  | 'Megaphone'
  | 'MessageCircle'
  | 'MonitorSmartphone'
  | 'Newspaper'
  | 'PenLine'
  | 'Plus'
  | 'Presentation'
  | 'Quote'
  | 'Radio'
  | 'Rows3'
  | 'Search'
  | 'Send'
  | 'Shield'
  | 'Smartphone'
  | 'Sparkles'
  | 'Tags'
  | 'Target'
  | 'Terminal'
  | 'TriangleAlert'
  | 'UsersRound'
  | 'Volume2'
  | 'Webhook';
