import type { AssetOriginType } from '../domain/index.ts';
import type { IconKey } from './icons.ts';
import { availableIn, CURRENT_RELEASE } from './release.ts';
import type { ReleaseId } from './release.ts';

/**
 * Tabs of the image picker (Drawer "Inserir imagem" / "Definir como destaque"). R1 ships "Enviar
 * arquivo" and "Link"; R2 adds the archive search ("Acervo", F2.9) and R6 image generation and
 * semantic search (F6.10, F6.9) by adding entries here, each producing assets of its origin.
 */

export type ImageSourceId = 'upload' | 'link' | 'archive' | 'generate' | 'semantic-search';

export type ImageSourceEntry = {
  id: ImageSourceId;
  /** Tab label. */
  label: string;
  icon: IconKey;
  since: ReleaseId;
  /** Origin of the assets this tab creates. */
  origin: AssetOriginType;
  /** Requirement that brings the tab ("F2.9"). */
  requirement?: string;
  /** Images generated by AI are labelled as such (README §6). */
  ai?: true;
};

export const IMAGE_SOURCES: readonly ImageSourceEntry[] = [
  { id: 'upload', label: 'Enviar arquivo', icon: 'Image', since: 'R1', origin: 'upload' },
  { id: 'link', label: 'Link', icon: 'Globe', since: 'R1', origin: 'url' },
  { id: 'archive', label: 'Acervo', icon: 'Archive', since: 'R2', origin: 'archive', requirement: 'F2.9' },
  { id: 'generate', label: 'Gerar com IA', icon: 'Sparkles', since: 'R6', origin: 'generated', requirement: 'F6.10', ai: true },
  { id: 'semantic-search', label: 'Busca semântica', icon: 'Search', since: 'R6', origin: 'archive', requirement: 'F6.9' },
];

/** Picker tabs of a release, in order. */
export function imageSourcesFor(release: ReleaseId = CURRENT_RELEASE): ImageSourceEntry[] {
  return availableIn(IMAGE_SOURCES, release);
}

export function imageSource(id: ImageSourceId): ImageSourceEntry | undefined {
  return IMAGE_SOURCES.find((entry) => entry.id === id);
}
