import {
  Activity,
  Archive,
  AtSign,
  BadgeCheck,
  BarChart3,
  Boxes,
  Building2,
  CalendarDays,
  Captions,
  ChartNoAxesColumn,
  CheckCircle2,
  ClipboardList,
  Clock,
  Download,
  FileSignature,
  FileText,
  FileVideo,
  Gauge,
  Globe,
  Image as ImageIcon,
  Inbox,
  LayoutDashboard,
  LayoutList,
  LayoutTemplate,
  ListChecks,
  Loader2,
  Mail,
  Megaphone,
  MessageCircle,
  MonitorSmartphone,
  Newspaper,
  PenLine,
  Plus,
  Presentation,
  Quote,
  Radio as RadioIcon,
  Rows3,
  Search,
  Send,
  Shield,
  Smartphone,
  Sparkles,
  Tags,
  Target,
  Terminal,
  TriangleAlert,
  UsersRound,
  Volume2,
  Webhook,
  type LucideIcon,
} from '@content-ventures/design-system/v3/icons';
import type { IconKey } from '@/registries';

/**
 * Registry icon keys → Design System icons. Registries stay pure data (string keys); this map is
 * the only place that turns a key into a drawable icon, with named imports so the bundle keeps
 * only the icons in use.
 */
export const ICONS: Record<IconKey, LucideIcon> = {
  Activity,
  Archive,
  AtSign,
  BadgeCheck,
  BarChart3,
  Boxes,
  Building2,
  CalendarDays,
  Captions,
  ChartNoAxesColumn,
  CheckCircle2,
  ClipboardList,
  Clock,
  Download,
  FileSignature,
  FileText,
  FileVideo,
  Gauge,
  Globe,
  Image: ImageIcon,
  Inbox,
  LayoutDashboard,
  LayoutList,
  LayoutTemplate,
  ListChecks,
  Loader2,
  Mail,
  Megaphone,
  MessageCircle,
  MonitorSmartphone,
  Newspaper,
  PenLine,
  Plus,
  Presentation,
  Quote,
  Radio: RadioIcon,
  Rows3,
  Search,
  Send,
  Shield,
  Smartphone,
  Sparkles,
  Tags,
  Target,
  Terminal,
  TriangleAlert,
  UsersRound,
  Volume2,
  Webhook,
};

export function iconFor(key: IconKey): LucideIcon {
  return ICONS[key];
}
